name: Lint

on:
  workflow_run:
    workflows: ["Install dependencies"]
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get node modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules

      - name: Lint
        run: npm run lint
 
 

