name: Lint

on:
  workflow_run:
    workflows: ["Install dependencies"]
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/install.yml

      - name: Lint
        run: npm run lint
 
 

