name: Release

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'The tag name of the release'
        required: true
        default: 'v0.0.0'
      releaseBody:
        description: 'The body of the release'
        required: true
        default: 'See the assets to download and install this version.'
      releaseDraft:
        description: 'Create a draft release'
        required: false
        default: true
      prerelease:
        description: 'Create a prerelease'
        required: false
        default: false

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - uses: ./.github/workflows/install.yml

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.event.inputs.tagName }}
          releaseName: 'App Name v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: ${{ github.event.inputs.releaseBody }}
          releaseDraft: ${{ github.event.inputs.releaseDraft }}
          prerelease: ${{ github.event.inputs.prerelease }}