name: Test

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  install:
    uses: ./.github/workflows/install.yml
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: npm run test