name: Test

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get node modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules

      - name: Test
        run: npm run test