name: Test

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 16.15.0
          pnpm-version: 7.9.4

      - name: Test
        run: pnpm test